//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMS.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbLibraryMSEntities : DbContext
    {
        public DbLibraryMSEntities()
            : base("name=DbLibraryMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAction> tblAction { get; set; }
        public virtual DbSet<tblAuthor> tblAuthor { get; set; }
        public virtual DbSet<tblBook> tblBook { get; set; }
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblEmployee> tblEmployee { get; set; }
        public virtual DbSet<tblMember> tblMember { get; set; }
        public virtual DbSet<tblPenal> tblPenal { get; set; }
        public virtual DbSet<tblSafe> tblSafe { get; set; }
        public virtual DbSet<tblAbout> tblAbout { get; set; }
        public virtual DbSet<tblContact> tblContact { get; set; }
        public virtual DbSet<tblMessages> tblMessages { get; set; }
    
        public virtual ObjectResult<string> BesatAuthor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BesatAuthor");
        }
    }
}
