//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblAuthor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAuthor()
        {
            this.tblBook = new HashSet<tblBook>();
        }
    
        public int Id { get; set; }
        [StringLength(40,ErrorMessage ="Yazar Adý 40 Karakterden Fazla Olamaz")]
        [Required(ErrorMessage ="Ad Alaný Zorunludur")]
        public string Name { get; set; }
        [StringLength(40, ErrorMessage = "Yazar Adý 40 Karakterden Fazla Olamaz")]
        [Required(ErrorMessage = "Soyad Alaný Zorunludur")]
        public string Surname { get; set; }
        public string Detail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBook> tblBook { get; set; }
    }
}
