//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPenal
    {
        public int Id { get; set; }
        public Nullable<int> Member { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Money { get; set; }
    
        public virtual tblAction tblAction { get; set; }
        public virtual tblMember tblMember { get; set; }
    }
}
